[package]
name = "vfs"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { workspace = true }
adt-query = { workspace = true }
slotmap = { version = "1.0", features = ["serde"] }

[dev-dependencies]
serde_json = { workspace = true }
